### ISSUE TITLE
navi14 installing tips

### ISSUE THREAD

**Issue by thefrol** [xuhuisheng/rocm-build#18]
finally compiled all supposed scripts for NAVI14 sucessfully! Thank you

for MIopen I needed some additional packages
libslite-dev
libboost-all-dev
texlive-latex-recommended
libbz2-dev
half
libghc-half-dev

So i am wondering if rocminfo and clinfo should show my 5500xt as agent. Now i cant see my gpu there. So maybe i should install drivers first or smth?

Thank you for your work and please explain what should i see in rocminfo and clinfo

**Comment by xuhuisheng** [comment]
The rocminfo should shows likes gfx1012

You may meet the PCIe atomics operation problems.
As ROCm team said that navi GPU need PCIe atomics supporting by both CPU and motherboard.
<https://github.com/RadeonOpenCompute/ROCm#supported-cpus>

You may see kernel logs by `dmesg | grep kfd`
Likes:
```
kfd: skipped device 1002:7300, PCI rejects atomics

```

**Comment by thefrol** [comment]
> [    2.694307] kfd kfd: amdgpu: skipped device 1002:7340, PCI rejects atomics

well a big pity ;(

Was hoping for elder generations dont need atomics as metioned here
`Beginning with ROCm 1.8, GFX9 GPUs (such as Vega 10) no longer require PCIe atomics. We have similarly opened up more options for number of PCIe lanes. GFX9 GPUs can now be run on CPUs without PCIe atomics and on older PCIe generations, such as PCIe 2.0. This is not supported on GPUs below GFX9, e.g. GFX8 cards in the Fiji and Polaris families.`

Well, great thanks for your work and support <3

**Comment by xuhuisheng** [comment]
The truth is only gfx9 didn't require PCIe atomics feature.
And gfx9 is the real offcial supporting series: gfx900, gfx906, gfx908, gfx90a.

Older card like gfx803, New cards like gfx101x, gfx103x, They all need the PCIe atomics feature.
Right now, I didn't know what the atomics features affects. It is appreciate if someone could told me how to like gfx803 ignore atomics requirement. :D

**Comment by thefrol** [comment]
Well looks like i need to find some atomics. Thank you!

**Comment by xuhuisheng** [comment]
2 months after last posts, I will close this issue, please reopen if there is any updates.
