### ISSUE TITLE
11.llvm-amdgpu.sh fails with recent linux kernel, cyclades removed from kernel headers

### ISSUE THREAD

**Issue by jkroll20** [xuhuisheng/rocm-build#20]
### Environment

| Hardware | description   |
|----------|---------------|
| GPU      | gfx803             |
| CPU      | ryzen7             |

| Software | version |
|----------|---------|
| OS       | debian bookworm       |
| ROCm     | 4.3       |
| Python   | 3.9.9       |
| Linux | 5.15.0-1-amd64 |

### What is the expected behavior

- build scripts run

### What actually happens

- llvm build script fails

### How to reproduce

- run 11.llvm-amdgpu.sh with a recent linux kernel

There is a dependency on something called cyclades in llvm. Cyclades has been removed from the linux kernel headers. With a recent kernel, the llvm build will fail. 

I applied this manually:
https://reviews.llvm.org/rG68d5235cb58f988c71b403334cd9482d663841ab

and it seems to be building now.

**Comment by xuhuisheng** [comment]
I have met this issue on ubuntu-21.04 dialy build with kernel-5.13, too.
Ubuntu-20.04 compiled well.

**Comment by xuhuisheng** [comment]
Looks like ROCm-5.0.0 had resolved this problem.

**Comment by xuhuisheng** [comment]
I will close this issue, if you still meet the problem, please reopen it.
