### ISSUE TITLE
21.rocfft.sh, CMAKE_BUILD_WITH_INSTALL_RPATH

### ISSUE THREAD

**Issue by jkroll20** [xuhuisheng/rocm-build#22]
### Environment

| Hardware | description   |
|----------|---------------|
| GPU      | gfx803             |
| CPU      | ryzen7             |

| Software | version |
|----------|---------|
| OS       | debian bookworm       |
| ROCm     | 4.3       |
| Python   | 3.9.9       |
| Linux | 5.15.0-1-amd64 |
| cmake | 3.22.1 |

### What is the expected behavior

- 21.rocfft.sh builds rocfft

### What actually happens

- build exits with error: ```CMake Error at library/src/CMakeLists.txt:62 (add_library):
  The install of the rocfft target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based or XCOFF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH
  variable may be set to avoid this relinking step. ```

### How to reproduce

- run 21.rocfft.sh

Adding `-DCMAKE_BUILD_WITH_INSTALL_RPATH=ON` to the cmake cmdline seems to fix the issue.

**Comment by xuhuisheng** [comment]
Maybe this is an issue for cmake-3.22?
I am using cmake-3.16.8 for the minimal required.

**Comment by xuhuisheng** [comment]
I will close this issue, if you still meet the problem, please reopen it.
