### ISSUE TITLE
22.rocblas.sh fails, 'cmake -lpthread'

### ISSUE THREAD

**Issue by jkroll20** [xuhuisheng/rocm-build#23]
### Environment

| Hardware | description   |
|----------|---------------|
| GPU      | gfx803             |
| CPU      | ryzen7             |

| Software | version |
|----------|---------|
| OS       | debian bookworm       |
| ROCm     | 4.3       |
| Python   | 3.9.9       |
| Linux | 5.15.0-1-amd64 |
| cmake | 3.22.1 |

### What is the expected behavior

- rocBLAS built

### What actually happens

- CMake Error: Unknown argument -lpthread
CMake Error: Run 'cmake --help' for all supported options.

### How to reproduce

- run 22.rocblas.sh

I think the `-lpthread` can just be removed from 22.rocblas.sh. It's already somewhere in the generated Makefiles as an argument to gcc.

**Comment by xuhuisheng** [comment]
I had remove -lpthread, looks ok.
