### ISSUE TITLE
Minor build issues on Debian bookworm

### ISSUE THREAD

**Issue by jkroll20** [xuhuisheng/rocm-build#24]
### Environment

| Hardware | description   |
|----------|---------------|
| GPU      | gfx803             |
| CPU      | ryzen7             |

| Software | version |
|----------|---------|
| OS       | debian bookworm       |
| ROCm     | 4.3       |
| Python   | 3.9.9       |
| Linux | 5.15.0-1-amd64 |
| cmake | 3.22.1 |

I'm currently trying to build rocm 4.5 for gfx803 using your feature/build branch. If I run into any more minor issues I'll report them here, instead of opening a new issue for every little thing.

BTW, thanks for your awesome work with the build scripts and especially support for the gfx803.

**Comment by jkroll20** [comment]
### 34.miopen.sh, half include dir

After adding `-DHALF_INCLUDE_DIR=$ROCM_GIT_DIR/half/include` the build script seems to work:

```
diff --git a/34.miopen.sh b/34.miopen.sh
index a78a069..55aa2dc 100644
--- a/34.miopen.sh
+++ b/34.miopen.sh
@@ -17,6 +17,7 @@ CXX=$ROCM_INSTALL_DIR/llvm/bin/clang++ cmake \
     -DCPACK_SET_DESTDIR=OFF \
     -DCPACK_PACKAGING_INSTALL_PREFIX=$ROCM_INSTALL_DIR \
     -DCMAKE_INSTALL_PREFIX=$ROCM_INSTALL_DIR \
+    -DHALF_INCLUDE_DIR=$ROCM_GIT_DIR/half/include \
     -G Ninja \
     $ROCM_GIT_DIR/MIOpen
 ninja
```

**Comment by xuhuisheng** [comment]
I think we could move half before the miopen, so the dependency issue could be resolved.

**Comment by xuhuisheng** [comment]
I will close this issue, if you still meet the problem, please reopen it.
