### ISSUE TITLE
How to Get This Working On An 18.04 Based System?

### ISSUE THREAD

**Issue by BloodyMess** [xuhuisheng/rocm-build#25]
I'm trying it on 18.04 now.

One thing I've run into is that the scripts don't gracefully handle paths with spaces in the name. The variables need to be enclosed in double quotes when they are used in the scripts.

For instance lines 5 & 6 of `00.rocm-core.sh` need to be like this:
```
mkdir -p "$ROCM_BUILD_DIR/rocm-core"
cd "$ROCM_BUILD_DIR/rocm-core"
```

There's probably more places besides those first few lines in the other scripts. I'm going through them now.

Also, I've created a convenience script to go through the scripts and execute them in order so I don't have to do it manually.

**Comment by BloodyMess** [comment]
Well, I've run into a couple of problems in the scripts:
1) All those instances of `sudo apt install` for various packages aren't OK. It's **_really bad_** to just haul off and install system-wide packages on your own. They **_really_** need to be removed, and the packages they install added to a list of dependencies/prerequisites in the readme file so the user can decide for themselves how to go about handling those things.

2) It turns out that you **_do_** have a hard dependency on 20.04 in the form of installing `python-is-python3`. I already have the symlink that that package creates, so I've just disabled it along with all the other instances of `sudo apt install`.

**Comment by xuhuisheng** [comment]
I had move `sudo apt install` from each of shells to a single install-dependency.sh.

And `python-is-pyhon3` need by repo on ubuntu-20.04, you can remove it on other version of ubuntu.

**Comment by xuhuisheng** [comment]
I will close this issue, if you still meet the problem, please reopen it.
